name: module_movies
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^6.0.3
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  google_fonts: ^3.0.1
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.0.0
  get_it: ^7.1.3
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  flutter_bloc: ^8.1.1
  firebase_crashlytics: ^2.8.13
  rxdart: ^0.27.1
  module_common:
    path: ../module_common
  module_tvseries:
    path: ../module_tvseries
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.8
  bloc_test: ^9.1.0
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

